name: @{package.name}
version: @{application.version}
summary: @{package.synopsis}
description: @{package.description}

confinement: strict
grade: stable

architectures: [amd64]

apps:
  filebot:
    command: desktop-launch $SNAP/filebot.sh
    plugs: [unity7, opengl, x11, home, removable-media, network, network-bind, pulseaudio, gsettings]

parts:
  filebot:
    plugin: dump
    source: filebot
  java:
    plugin: nil
    stage-packages: [openjdk-8-jre, openjfx, jayatana]
    after: [desktop-gtk2]
  native:
    plugin: nil
    stage-packages: [libmediainfo0v5, libchromaprint-tools, curl]
